### ISSUE TITLE
fm.last.musicbrainz.coverart missing "LINER" value for CoverArtType enum

### ISSUE THREAD

**Issue by marcoc1712** [lastfm/coverartarchive-api#3]
see: https://musicbrainz.org/doc/Cover_Art/Types

**Comment by marcoc1712** [comment]
The code here is updated, but problem is the version in Maven repo is not. Probably you should release code with upgraded version.

**Comment by massdosage** [comment]
Yes, someone with commit rights needs to do a release to Maven central to get those changes from master into an officially released version. I'm not sure any of the original committers who set that all up are still involved here. I'd be happy to help if someone can re-add me as a committer ("external contributor" should do the trick) or I can describe the steps needed.

**Comment by massdosage** [comment]
I now have "external contributor" rights, taking a look if I can still do an official release.

**Comment by massdosage** [comment]
OK, I'm having an issue with the push to Sonatype for Maven central, possibly because I don't have my GPG  keys set up properly on this machine. I'll need to try from elsewhere but this will have to wait until later in the week.

**Comment by massdosage** [comment]
I released these changes in version 2.1.1 today, it should now be available in Sonatype and Maven Central. Thanks for pointing this out.
